kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argocdk8s
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 32073
      hostPort: 32073
    - containerPort: 32074
      hostPort: 32074
