apiVersion: argoproj.io/v1alpha1

kind: Application
metadata:
  name: application-from-scratch
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: project-resource-whitelist
  source:
    helm:
      releaseName: application-from-helm
      valueFiles:
        - custom-values.yaml
      # parameters:
      #   - name: "replicaCount"
      #     value: "3"
    path: v03/helm/nginx
    repoURL: https://github.com/chengxufeng1994/gitops-argocd.git
    targetRevision: main
