apiVersion: argoproj.io/v1alpha1

kind: Application
metadata:
  name: application-destination-restriction
spec:
  destination:
    namespace: prod 
    server: https://kubernetes.default.svc
  project: project-destination-restriction
  source:
    path: v03/helm/nginx
    targetRevision: main
    repoURL: https://github.com/chengxufeng1994/gitops-argocd.git
